name: Build and Deploy

on:
  push:
    branches:
      - blog_src

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.58.0'

    - name: Build
      run: hugo --minify
    - name: Deploy to GitHub IO

      uses: docker://peaceiris/gh-pages:v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
